dbphp/coders.Rockers.Moe.FINAL/routes/web.php
<?php

use App\Http\Controllers\AutoController;
use App\Http\Controllers\HerstellerController;
use App\Http\Controllers\ModellController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('/autos', AutoController::class);
Route::resource('/hersteller', HerstellerController::class);
Route::resource('/modells', ModellController::class);

dbphp/coders.Rockers.Moe.FINAL/app/Models/Hersteller.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Hersteller extends Model
{
    use HasFactory;

    protected $table = 'hersteller';


    protected $fillable = ['id', 'name'];

    public function autos()
    {
        return $this->hasMany(Auto::class);
    }

    public $timestamps = false;
}

dbphp/coders.Rockers.Moe.FINAL/app/Http/Controllers/HerstellerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Autohaus;
use App\Models\Hersteller;
use Illuminate\Http\Request;

class HerstellerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $hersteller = Hersteller::all();
        return view('hersteller.index',compact('hersteller'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $hersteller = Hersteller::all();
        $autohauser = Autohaus::all();
        return view('hersteller.create',compact('hersteller','autohauser'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'id'=> 'required|numeric',
            'name'=> 'required|alpha_num',


        ]);



        $hersteller = Hersteller::create([
            'id' => $request->id,
            'name' => $request->name


        ]);

        return view('hersteller.show', compact('hersteller'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Hersteller $hersteller)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Hersteller $hersteller)
    {
        return view('hersteller.edit', compact('hersteller'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Hersteller $hersteller)
    {



        // Validiere die Eingaben des Benutzers
        $request->validate([
            'id'=> 'required|numeric',
            'name'=> 'required|alpha_num',
        ]);

        // Aktualisiere die Daten des Produkts mit den übermittelten Daten
        Hersteller::where('id',$hersteller->id)->   update([
            'id' => $request->id,
            'name' => $request->name,
        ]);

        // Zeige eine Erfolgsmeldung und leite zur Produktliste weiter
        return redirect()->route('hersteller.index')->with('success', 'Hersteller erfolgreich aktualisiert.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Hersteller $hersteller)
    {
        $hersteller = Hersteller::find($hersteller->id);
        $hersteller -> delete();

        return redirect()->route('hersteller.index')->with('success', 'Hersteller erfolgreich gelöscht.');

    }
}

dbphp/coders.Rockers.Moe.FINAL/resources/views/hersteller/create.blade.php
@extends('layout.default')

@section('content')
    <h1>Neuen Hersteller hinzufügen</h1>
    <form method="POST" action="/hersteller">
        @csrf
        <div class="form-group">
            <label for="id">ID:</label>
            <input type="number" name="id" id="id" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>

                @foreach($hersteller as $hersteller)
                    <option value="{{ $hersteller->id }}">{{ $hersteller->name }}</option>
                @endforeach


        <button type="submit" class="btn btn-primary">Hersteller hinzufügen</button>
    </form>
@endsection

dbphp/coders.Rockers.Moe.FINAL/resources/views/hersteller/edit.blade.php
@extends('layout.default')

@section('content')

    <h1>Hersteller bearbeiten</h1>

    <form method="POST" action="{{ route('hersteller.update', $hersteller) }}">

        @csrf

        @method('PUT')

        <div class="form-group">

            <label for="id">id:</label>

            <input type="number" name="id" id="id" class="form-control" value="{{ $hersteller->id }}" required readonly>

        </div>

        <div class="form-group">

            <label for="name">NAME:</label>

            <input type="alpha_num" name="name" id="name" class="form-control" value="{{ $hersteller->name  }}" required>

        </div>




        <button type="submit" class="btn btn-primary">Hersteller aktualisieren</button>

    </form>

@endsection

dbphp/coders.Rockers.Moe.FINAL/resources/views/hersteller/index.blade.php
@extends('layout.default')

@section('content')
    <h1>Autoliste</h1>
    <a href="{{ route('autos.create') }}" class="btn btn-primary mb-2">Neues Auto hinzufügen</a>
    <a href="{{ route('hersteller.create') }}" class="btn btn-primary mb-2">Neuer Hersteller hinzufügen</a>
    <a href="{{ route('modells.create') }}" class="btn btn-primary mb-2">Neues Modell hinzufügen</a>

    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Aktionen</th>

        </tr>
        </thead>
        <tbody>

        @foreach($hersteller as $hersteller)
            <tr>
                <td>{{ $hersteller->id }}</td>
                <td>{{ $hersteller->name }}</td>

                <td>

                    <a href="{{ route('hersteller.edit', $hersteller) }}" class="btn btn-warning">Bearbeiten</a>


                    <form action="{{ route('hersteller.destroy', $hersteller) }}" method="POST" style="display: inline;">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Sind Sie sicher?')">Löschen</button>
                    </form>
                </td>

            </tr>
        @endforeach
        </tbody>
    </table>

@endsection

dbphp/coders.Rockers.Moe.FINAL/resources/views/hersteller/show.blade.php
@extends('layout.default')

@section('content')
    <h1>ID : {{ $hersteller -> id }}</h1>
    <p>NAME : {{ $hersteller ->  name}}</p>

@endsection